name: CI
on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['7.3', '7.4', '8.0']
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
      - name: Install dependencies
        run: composer install
      - name: Run PSR check on src
        run: vendor/bin/phpcs src
      - name: Run PSR check on tests
        run: vendor/bin/phpcs tests
      - name: Run Unit tests
        run: vendor/bin/phpunit tests
